version: '3'
services:

  db:
    image: postgis/postgis:14-3.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
     - 5432:5432
    volumes:
     - ./test_vol:/test_vol
     - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pg_data: