version: '3'
services:

  db:
    image: postgis/postgis:14-3.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
     - 5433:5432
    volumes:
     - ./test_vol:/test_vol
     - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
      
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 4000:3000

volumes:
  pg_data: