version: '3'
services:

  db:
    image: postgis/postgis:14-3.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
     - 127.0.0.1:5433:5432
    volumes:
     - ./test_vol:/test_vol
     - pg_alpine_test_pg_data:/var/lib/postgresql/data
    networks:
      - pg-network

networks:
  pg-network:
    external: true

volumes:
  pg_alpine_test_pg_data:
    external: true